<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!--base footprint-->    
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>

    <!--base link-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>        
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                            xyz="0 0 0.1" rpy="0 0 0"/>
    </link>

    <!-- lidar
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white"/>
        </visual>
        <xacro:wheel_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                            xyz="0 0 0" rpy="0 0 0"/> 
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0 0 0.225" rpy="0 0 0"/>
    </joint>-->

    <!--wheel xacro macro-->
    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="0.1"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
            <xacro:wheel_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                                xyz="0 0 0" rpy="1.57 0 0"/>            
        </link>
    </xacro:macro>

    <xacro:wheel prefix="right" />
    <xacro:wheel prefix="left" />

    <!--left wheel-->

    <joint name="left_wheel_link" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="${-base_length/4.0} 0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <!--right wheel-->

    <joint name="right_wheel_link" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="${-base_length/4.0} -0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <!--caster wheel-->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:caster_wheel_inertia m="0.5" r="${wheel_radius/2.0}"
                                    xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <joint name="caster_wheel_link" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel" />
        <origin xyz="${base_length/3.0} 0 -0.05" rpy="0 0 0"/>
    </joint>
</robot>