<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!--define colors -->
    <material name="grey">
        <color rgba="0.7 0.7 0.7 1"/>
    </material>

    <material name="green">
        <color rgba="0 0.6 0.0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <!--base footprint-->    
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0.1 0" rpy="0 0 0"/>
    </joint>

    <!--base link-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
    </link>

    <!-- lidar -->
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white"/>
        </visual>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0 0 0.225" rpy="0 0 0"/>
    </joint>
    
    <!--left wheel-->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="left_wheel_link" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="${-base_length/4.0} 0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <!--right wheel-->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="right_wheel_link" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="${-base_length/4.0} -0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <!--caster wheel-->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="caster_wheel_link" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel" />
        <origin xyz="${base_length/3.0} 0 -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

</robot>